-- ALTER USER 'tempuser'@'localhost' PASSWORD EXPIRE;
-- ALTER USER 'tempuser'@'localhost' PASSWORD EXPIRE INTERVAL 90 DAY;
-- ALTER USER 'tempuser'@'localhost' PASSWORD EXPIRE NEVER;
-- ALTER USER 'tempuser'@'localhost' PASSWORD EXPIRE DEFAULT;
-- DROP USER 'tempuser'@'localhost';